apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: nvmesh-clear-db-job
  name: nvmesh-clear-db-job
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: nvmesh-clear-db-job
  template:
    metadata:
      labels:
        job-name: nvmesh-clear-db-job
    spec:
      restartPolicy: OnFailure
      containers:
      - image: registry.excelero.com/nvmesh-mongo-instance:placeholder
        command:
          - "mongo"
        args:
          - "<mongo-server-address>"
          - "--eval"
          - "db.dropDatabase()"
        imagePullPolicy: Always
        name: nvmesh-clear-db-job
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: excelero-registry-cred
      terminationGracePeriodSeconds: 30
