apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-name
  namespace: system
  labels:
    control-plane: operator-name
spec:
  selector:
    matchLabels:
      control-plane: operator-name
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: operator-name
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: operator-name:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
