apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvmesh-operator
  labels:
    app: nvmesh-operator
spec:
  selector:
    matchLabels:
      app: nvmesh-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: nvmesh-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: excelero/nvmesh-operator:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
