kind: ConfigMap
apiVersion: v1
metadata:
  name: nvmesh-core-config
data:
  fileServer.address: "https://10.0.1.57:3000"
  fileServer.skipCheckCertificate: "true"
  nvmesh.version: ""
  nvmesh.conf: |-
    MANAGEMENT_PROTOCOL="https"
    MANAGEMENT_SERVERS="nvmesh-management-0.nvmesh-management-ws.default.svc.cluster.local:4001"
    MCS_LOG_TO_STDOUT="True"
    MCS_LOGGING_LEVEL="VERBOSE"
    MCS_LOGGING_VERBOSE_TYPES="MGMT>*,*>MGMT"
    AGENT_LOGGING_LEVEL="DEBUG"
    AGENT_LOG_TO_STDOUT="True"