kind: ConfigMap
apiVersion: v1
metadata:
  name: nvmesh-core-config
data:
  fileServer.address: "placeholder"
  fileServer.skipCheckCertificate: "false"
  nvmesh.version: "placeholder"
  nvmesh.conf: |-
    K8S_ENV="True"
    MANAGEMENT_PROTOCOL="https"
    MANAGEMENT_SERVERS="nvmesh-management-0.nvmesh-management-ws.<ns>.svc.cluster.local:4001"
    MCS_LOG_TO_STDOUT="True"
    MCS_LOGGING_LEVEL="VERBOSE"
    MCS_LOGGING_VERBOSE_TYPES="MGMT>*,*>MGMT"
    AGENT_LOGGING_LEVEL="DEBUG"
    AGENT_LOG_TO_STDOUT="True"
    CONFIG_PROFILE_ID="cluster_default"
    CONFIG_PROFILE_NAME="Cluster Default"
    CONFIG_PROFILE_VERSION="1"
  modprobe.d: |-
    # override modules parameters here. The contents of this field will be written to /etc/modprobe.d/zz_nvmesh_from_configmap.conf
    # Example:
    # options <module name> arg_name=value
