apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kmod-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kmod-manager
  namespace: default
subjects:
- kind: ServiceAccount
  name: kmod-manager
  namespace: default
userNames:
- system:serviceaccount:default:kmod-manager