kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nvmesh-mcs-agent
spec:
  selector:
    matchLabels:
      app: nvmesh-mcs-agent
  template:
    metadata:
      name: nvmesh-mcs-agent
      labels:
        app: nvmesh-mcs-agent
        nvmesh.excelero.com/component: mcs-agent
    spec:
      serviceAccountName: nvmesh-cluster
      imagePullSecrets:
        - name: excelero-registry-cred
      nodeSelector:
       nvmesh.excelero.com/nvmesh-client: ""
      # hostNetwork: true allows the pod to have the hostname of the node where the pod is run
      hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet allows the pod to have cluster DNS to be able to resolve service dns names. this is needed only when hostNetwork is true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: mcs
          image: nvmesh-mcs:placeholder
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/init.sh mcs"]
          env:
          - name: NVMESH_CONF
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: nvmesh.conf
          - name: NVMESH_VERSION
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: nvmesh.version
          - name: KMOD_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: fileServer.address
          - name: NO_CHECK_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: fileServer.skipCheckCertificate
          - name: KMOD_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: nvmesh-file-server-cred
                key: username
          - name: KMOD_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nvmesh-file-server-cred
                key: password
          volumeMounts:
            - name: nvmesh-conf
              mountPath: "/etc/opt/NVMesh"
            - name: var-run-nvmesh
              mountPath: /var/run/NVMesh/
            - name: var-bin-nvmesh
              mountPath: /var/bin/nvmesh
            - name: opt-nvmesh
              mountPath: /host/opt/NVMesh
            - name: var-opt-nvmesh
              mountPath: /var/opt/NVMesh
            - name: opt-nvmesh-operator
              mountPath: /opt/nvmesh-operator
          securityContext:
            privileged: true
        - name: agent
          image: nvmesh-mcs:placeholder
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/init.sh agent"]
          env:
          - name: NVMESH_CONF
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: nvmesh.conf
          - name: NVMESH_VERSION
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: nvmesh.version
          - name: KMOD_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: fileServer.address
          - name: NO_CHECK_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: nvmesh-core-config
                key: fileServer.skipCheckCertificate
          - name: KMOD_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: nvmesh-file-server-cred
                key: username
          - name: KMOD_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nvmesh-file-server-cred
                key: password
          volumeMounts:
            - name: nvmesh-conf
              mountPath: "/etc/opt/NVMesh"
            - name: var-run-nvmesh
              mountPath: /var/run/NVMesh/
            - name: dev
              mountPath: /dev/
            - name: opt-nvmesh
              mountPath: /opt/NVMesh
            - name: opt-nvmesh-operator
              mountPath: /opt/nvmesh-operator
      volumes:
        - name: nvmesh-conf
          configMap:
            name: nvmesh-core-config
            items:
            - key: "nvmesh.conf"
              path: ".nvmesh.conf"
        - name: var-run-nvmesh
          hostPath:
            path: /var/run/NVMesh/
        - name: var-bin-nvmesh
          hostPath:
            path: /var/bin/nvmesh
        - name: dev
          hostPath:
            path: /dev/
        - name: opt-nvmesh
          hostPath:
            path: /opt/NVMesh
        - name: opt-nvmesh-operator
          hostPath:
            path: /opt/nvmesh-operator
        - name: var-opt-nvmesh
          hostPath:
            path: /var/opt/NVMesh/