apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvmesh-client
  labels:
    k8s-app: nvmesh-client
spec:
  selector:
    matchLabels:
      app: nvmesh-client
      nvmesh.driver-container-type: client
  template:
    metadata:
      labels:
        app: nvmesh-client
        nvmesh.driver-container-type: client
        nvmesh.excelero.com/component: client
    spec:
      serviceAccountName: nvmesh-cluster
      nodeSelector:
        nvmesh.excelero.com/nvmesh-client: ""
      imagePullSecrets:
        - name: excelero-registry-cred
      hostPID: true
      hostNetwork: true
      # terminationGracePeriod of 1 Hours
      terminationGracePeriodSeconds: 3600
      containers:
        - name: driver-container
          image: nvmesh-driver-container:placeholder
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/init.sh --type client --insert --remove-on-terminate --wait"]
          securityContext:
            privileged: true
          env:
            - name: NVMESH_VERSION
              value: placeholder
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: password
          volumeMounts:
            - name: nvmesh-conf
              mountPath: /coreConfigMap
            - name: modprobe-d-conf
              mountPath: /etc/modprobe.d/zz_nvmesh_from_configmap.conf
              subPath: zz_nvmesh_from_configmap.conf
            - name: device-dir
              mountPath: /dev
            - name: lib-modules-dir
              mountPath: /host/lib/modules
            - name: var
              mountPath: /host/var/
            - name: opt-nvmesh
              mountPath: /opt/NVMesh/
            - name: host-bin
              mountPath: /host/bin/
            - name: host-sbin
              mountPath: /host/sbin/
            - name: opt-nvmesh-operator
              mountPath: /opt/nvmesh-operator
            - name: var-log-nvmesh
              mountPath: /var/log/NVMesh/
        - name: tracer
          image: nvmesh-tracer:placeholder
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/init.sh"]
          securityContext:
            privileged: true
          env:
            - name: NVMESH_VERSION
              value: placeholder
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: password
          volumeMounts:
            - name: var-run-nvmesh
              mountPath: /var/run/NVMesh/
            - name: var-log-nvmesh
              mountPath: /var/log/NVMesh/
            - name: host-bin
              mountPath: /host/bin/
            - name: host-sbin
              mountPath: /host/sbin/
            - name: opt-nvmesh
              mountPath: /opt/NVMesh
            - name: opt-nvmesh-operator
              mountPath: /opt/nvmesh-operator
      volumes:
        - name: nvmesh-conf
          configMap:
            name: nvmesh-core-config
            items:
            - key: "nvmesh.conf"
              path: "nvmesh.conf"
        - name: modprobe-d-conf
          configMap:
            name: nvmesh-core-config
            items:
              - key: modprobe.d
                path: zz_nvmesh_from_configmap.conf
        - name: device-dir
          hostPath:
            path: /dev
        - name: lib-modules-dir
          hostPath:
            path: /lib/modules
        - name: var
          hostPath:
            path: /var
        - name: opt-nvmesh
          hostPath:
            path: /opt/NVMesh
        - name: opt-nvmesh-operator
          hostPath:
            path: /opt/nvmesh-operator
        - name: host-bin
          hostPath:
            path: /bin
        - name: host-sbin
          hostPath:
            path: /sbin
        - name: var-log-nvmesh
          hostPath:
            path: /var/log/NVMesh/
        - name: var-run-nvmesh
          hostPath:
            path: /var/run/NVMesh/
