apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvmesh-client-driver-container
  labels:
    k8s-app: nvmesh-client-driver-container
spec:
  selector:
    matchLabels:
      name: nvmesh-client-driver-container
      nvmesh.driver-container-type: client
  template:
    metadata:
      labels:
        name: nvmesh-client-driver-container
        nvmesh.driver-container-type: client
    spec:
      nodeSelector:
        nvmesh.excelero.com/nvmesh-client: ""
      imagePullSecrets:
        - name: excelero-registry-cred
      containers:
        - name: driver-container
          image: image-registry.openshift-image-registry.svc:5000/default/nvmesh-driver-container:dev
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "/init.sh --type client --insert --remove-on-terminate --wait"]
          securityContext:
            privileged: true
          env:
            - name: NVMESH_VERSION
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: nvmesh.version
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-cred
                  key: password
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: lib-modules-dir
              mountPath: /host/lib/modules
            - name: var
              mountPath: /host/var/
            - name: opt-nvmesh
              mountPath: /opt/NVMesh/
            - name: host-bin
              mountPath: /host/bin/
            - name: host-sbin
              mountPath: /host/sbin/
          # terminationGracePeriodSeconds - one hour
          terminationGracePeriodSeconds: 3600
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
        - name: lib-modules-dir
          hostPath:
            path: /lib/modules
        - name: var
          hostPath:
            path: /var
        - name: opt-nvmesh
          hostPath:
            path: /opt/NVMesh
        - name: host-bin
          hostPath:
            path: /bin
        - name: host-sbin
          hostPath:
            path: /sbin
