apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvmesh-target-driver-container
  labels:
    k8s-app: nvmesh-target-driver-container
spec:
  selector:
    matchLabels:
      name: nvmesh-driver-container
      nvmesh.driver-container-type: target
  template:
    metadata:
      labels:
        name: nvmesh-driver-container
        nvmesh.driver-container-type: target
    spec:
      nodeSelector:
        nvmesh.excelero.com/nvmesh-target: ""
      hostPID: true
      hostNetwork: true
      imagePullSecrets:
        - name: excelero-registry-cred
      containers:
        - name: driver-container
          image: nvmesh-driver-container:dev
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "/init.sh --type target --insert --remove-on-terminate --wait"]
          securityContext:
            privileged: true
          env:
            - name: NVMESH_VERSION
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: nvmesh.version
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-cred
                  key: password
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: lib-modules-dir
              mountPath: /host/lib/modules
            - name: var
              mountPath: /host/var/
            - name: etc-infiniband
              mountPath: /etc/infiniband
            - name: ofed-info
              mountPath: /bin/ofed_info
          terminationGracePeriodSeconds: 3600
        - name: toma
          image: nvmesh-toma
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "/init.sh"]
          env:
            - name: NVMESH_VERSION
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: nvmesh.version
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-cred
                  key: password
          securityContext:
            privileged: true
          volumeMounts:
            - name: var-run-nvmesh
              mountPath: /var/run/NVMesh/
            - name: etc-opt-nvmesh
              mountPath: /etc/opt/NVMesh/
            - name: var-opt-nvmesh
              mountPath: /var/opt/NVMesh/
            - name: etc-libibverbs
              mountPath: /etc/libibverbs.d/
            - name: lib-libibverbs
              mountPath: /usr/lib64/libibverbs/
            - name: libibverbs-mlx5
              mountPath: /usr/lib64/libmlx5.so.1.11.26.0
            - name: sys
              mountPath: /sys/
            - name: dev
              mountPath: /dev/
            - name: ofed-info
              mountPath: /bin/ofed_info
        - name: tracer
          image: nvmesh-tracer
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "/init.sh"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: var-run-nvmesh
              mountPath: /var/run/NVMesh/
            - name: tracer-logs
              mountPath: /var/log/NVMesh/
            - name: ofed-info
              mountPath: /bin/ofed_info
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
        - name: lib-modules-dir
          hostPath:
            path: /lib/modules
        - name: var
          hostPath:
            path: /var
        - name: var-run-nvmesh
          hostPath:
            path: /var/run/NVMesh/
        - name: var-opt-nvmesh
          hostPath:
            path: /var/opt/NVMesh/
        - name: etc-opt-nvmesh
          hostPath:
            path: /etc/opt/NVMesh/
        - name: etc-libibverbs
          hostPath:
            path: /etc/libibverbs.d/
        - name: lib-libibverbs
          hostPath:
            path: /usr/lib64/libibverbs/
        - name: libibverbs-mlx5
          hostPath:
            path: /usr/lib64/libmlx5.so.1.11.26.0
        - name: sys
          hostPath:
            path: /sys/
        - name: dev
          hostPath:
            path: /dev/
        - name: tracer-logs
          hostPath:
            path: /var/log/NVMesh/
        - name: etc-infiniband
          hostPath:
            path: /etc/infiniband
        - name: ofed-info
          hostPath:
            path: /bin/ofed_info