apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvmesh-target-driver-container
  labels:
    k8s-app: nvmesh-target-driver-container
spec:
  selector:
    matchLabels:
      name: nvmesh-target-driver-container
      nvmesh.driver-container-type: target
  template:
    metadata:
      labels:
        name: nvmesh-target-driver-container
        nvmesh.driver-container-type: target
        nvmesh.excelero.com/component: target
    spec:
      serviceAccountName: nvmesh-cluster
      imagePullSecrets:
        - name: excelero-registry-cred
      nodeSelector:
        nvmesh.excelero.com/nvmesh-target: ""
        nvmesh.excelero.com/nvmesh-client: ""
      hostPID: true
      hostNetwork: true
      containers:
        - name: driver-container
          image: nvmesh-driver-container:placeholder
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/init.sh --type target --insert --remove-on-terminate --wait"]
          securityContext:
            privileged: true
          env:
            - name: NVMESH_VERSION
              value: placeholder
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: password
          volumeMounts:
            - name: nvmesh-conf
              mountPath: "/etc/opt/NVMesh"
            - name: opt-nvmesh-operator
              mountPath: /opt/nvmesh-operator
            - name: device-dir
              mountPath: /dev
            - name: lib-modules-dir
              mountPath: /host/lib/modules
            - name: var
              mountPath: /host/var/
            - name: opt-nvmesh
              mountPath: /opt/NVMesh
            - name: host-bin
              mountPath: /host/bin/
            - name: host-sbin
              mountPath: /host/sbin/
          terminationGracePeriodSeconds: 3600
        - name: toma
          image: nvmesh-toma:placeholder
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/init.sh"]
          env:
            - name: NVMESH_VERSION
              value: placeholder
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: password
          securityContext:
            privileged: true
          volumeMounts:
            - name: nvmesh-conf
              mountPath: "/etc/opt/NVMesh"
            - name: opt-nvmesh-operator
              mountPath: /opt/nvmesh-operator
            - name: var-run-nvmesh
              mountPath: /var/run/NVMesh/
            - name: var-opt-nvmesh
              mountPath: /var/opt/NVMesh/
            - name: sys
              mountPath: /sys/
            - name: dev
              mountPath: /dev/
            - name: host-bin
              mountPath: /host/bin/
            - name: host-sbin
              mountPath: /host/sbin/
            - name: opt-nvmesh
              mountPath: /opt/NVMesh
        - name: tracer
          image: nvmesh-tracer:placeholder
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/init.sh"]
          securityContext:
            privileged: true
          env:
            - name: NVMESH_VERSION
              value: placeholder
            - name: KMOD_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.address
            - name: NO_CHECK_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: nvmesh-core-config
                  key: fileServer.skipCheckCertificate
            - name: KMOD_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: username
            - name: KMOD_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-file-server-cred
                  key: password
          volumeMounts:
            - name: var-run-nvmesh
              mountPath: /var/run/NVMesh/
            - name: tracer-logs
              mountPath: /var/log/NVMesh/
            - name: host-bin
              mountPath: /host/bin/
            - name: host-sbin
              mountPath: /host/sbin/
            - name: opt-nvmesh
              mountPath: /opt/NVMesh
            - name: opt-nvmesh-operator
              mountPath: /opt/nvmesh-operator
      volumes:
        - name: nvmesh-conf
          configMap:
            name: nvmesh-core-config
            items:
            - key: "nvmesh.conf"
              path: ".nvmesh.conf"
        - name: device-dir
          hostPath:
            path: /dev
        - name: lib-modules-dir
          hostPath:
            path: /lib/modules
        - name: var
          hostPath:
            path: /var
        - name: var-run-nvmesh
          hostPath:
            path: /var/run/NVMesh/
        - name: var-opt-nvmesh
          hostPath:
            path: /var/opt/NVMesh/
        - name: opt-nvmesh-operator
          hostPath:
            path: /opt/nvmesh-operator
        - name: etc-opt-nvmesh
          hostPath:
            path: /etc/opt/NVMesh/
        - name: sys
          hostPath:
            path: /sys/
        - name: dev
          hostPath:
            path: /dev/
        - name: tracer-logs
          hostPath:
            path: /var/log/NVMesh/
        - name: opt-nvmesh
          hostPath:
            path: /opt/NVMesh
        - name: host-bin
          hostPath:
            path: /bin
        - name: host-sbin
          hostPath:
            path: /sbin