apiVersion: nvmesh.excelero.com/v1
kind: NVMesh
metadata:
  name: cluster1
spec:
  core:
    azureOptimized: true
    configuredNICs: ib0
    version: 2.4.1-IB
  csi:
    version: v1.2.0
  management:
    version: 2.4.1