apiVersion: nvmesh.excelero.com/v1
kind: NVMesh
metadata:
  name: cluster1
spec:
  core:
    tcpOnly: true
    configuredNICs: ens4f0
    version: 2.4.1-TCP
  csi:
    version: v1.2.0
  management:
    version: 2.4.1