apiVersion: nvmesh.excelero.com/v1
kind: NVMesh
metadata:
  name: cluster1
spec:
  core:
    version: 2.2.1
    tcpOnly: true
    configuredNICs: eth0
  csi:
    controllerReplicas: 1
    version: v1.1.4-7
  management:
    mongoDB:
      replicas: 1
    replicas: 1
    version: 2.2.0
  debug:
    imagePullPolicyAlways: true
    containersKeepRunningAfterFailure: true
    debugJobs: false
