kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-nvmesh-psp
rules:
  - apiGroups: ["policy"]
    resourceNames: ["psp.nvmesh.privileged"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nvmesh-operator-use-psp
subjects:
  - kind: ServiceAccount
    name: nvmesh-operator
    # the namespace where the operator is deployed
    namespace: test-operator
roleRef:
  kind: ClusterRole
  name: use-nvmesh-psp
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nvmesh-csi-driver-use-psp
subjects:
  - kind: ServiceAccount
    name: nvmesh-csi-driver
    # the namespace where the operator is deployed
    namespace: test-operator
roleRef:
  kind: ClusterRole
  name: use-nvmesh-psp
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nvmesh-cluster-use-psp
subjects:
  - kind: ServiceAccount
    name: nvmesh-cluster
    # the namespace where the operator is deployed
    namespace: test-operator
roleRef:
  kind: ClusterRole
  name: use-nvmesh-psp
  apiGroup: rbac.authorization.k8s.io


