apiVersion: v1
kind: Service
metadata:
  name: nvmesh-management-svc-0
  labels:
    app: nvmesh-management
spec:
  type: ClusterIP
  selector:
    app: nvmesh-management
    statefulset.kubernetes.io/pod-name: nvmesh-management-0
  ports:
  - name: ws
    protocol: TCP
    port: 4001
    targetPort: ws
  - name: stats-0
    protocol: TCP
    port: 4002
    targetPort: 4002
  - name: stats-1
    protocol: TCP
    port: 4003
    targetPort: 4003
  - name: stats-2
    protocol: TCP
    port: 4004
    targetPort: 4004
  - name: stats-3
    protocol: TCP
    port: 4005
    targetPort: 4005
  - name: stats-4
    protocol: TCP
    port: 4006
    targetPort: 4006