apiVersion: v1
kind: Service
metadata:
  name: nvmesh-management-gui
spec:
  type: ClusterIP
  selector:
    app: nvmesh-management
  ports:
  - name: "gui"
    protocol: TCP
    port: 4000
    targetPort: gui

  # make sure that connections from a particular client are passed to the same Pod each time
  # without this setting nvmesh-management will reject the login accessToken
  sessionAffinity: ClientIP
