operator:
  version: 0.7.0
  release: 26
  channel: beta
  image_name: nvmesh-operator
  #repo: registry.connect.redhat.com/excelero
  repo: docker.io/excelero
bundle:
  version: 0.7.0
  release: 42
  dev:
    bundle_image_name: "docker.io/excelero/dev-os-bundle"
    index_build: 2
    index_image_name: "docker.io/excelero/dev-os-catalog-source-index"
