operator:
  version: 0.8.0
  release: 18
  channel: beta
  image_name: nvmesh-operator
  core_image_tag: 0.8.0-66
  production_repo: registry.connect.redhat.com/excelero
  dev_repo: registry.excelero.com/dev
bundle:
  version: 0.8.0
  release: 11
  dev:
    bundle_image_name: "registry.excelero.com/dev/dev-os-bundle"
    index_image_name: "registry.excelero.com/dev/dev-os-catalog-source-index"
  alm-example:
    # This will be embedded into the bundle manifest,
    # The RedHat scan server will use these versions for the certification CI
    # And they will also be the default values in the OpenShift Web UI
    apiVersion: nvmesh.excelero.com/v1
    kind: NVMesh
    metadata:
      name: cluster1
    spec:
      core:
        azureOptimized: true
        version: 2.2.1
      csi:
        controllerReplicas: 1
        version: v1.1.7
      management:
        mongoDB:
          replicas: 1
        replicas: 1
        version: 2.2.1-1