operator:
  version: 0.7.0
  release: 2
  channel: beta
bundle:
  version: 0.7.0
  release: 5
  dev:
    bundle_image_name: "docker.io/excelero/dev-os-bundle"
    bundle_build: 1
    index_image_name: "docker.io/excelero/dev-os-catalog-source-index"
