# permissions for end users to view nvmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvmesh-viewer-role
rules:
- apiGroups:
  - nvmesh.excelero.com
  resources:
  - nvmeshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvmesh.excelero.com
  resources:
  - nvmeshes/status
  verbs:
  - get
