# permissions for end users to edit nvmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvmesh-editor-role
rules:
- apiGroups:
  - nvmesh.excelero.com
  resources:
  - nvmeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nvmesh.excelero.com
  resources:
  - nvmeshes/status
  verbs:
  - get
