apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-kubernetes-operator
  namespace: nvmesh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mongodb-kubernetes-operator
    spec:
      containers:
      - command:
        - mongodb-kubernetes-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: mongodb-kubernetes-operator
        - name: AGENT_IMAGE
          value: quay.io/mongodb/mongodb-agent:10.15.1.6468-1
        - name: PRE_STOP_HOOK_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.1
        image: quay.io/mongodb/mongodb-kubernetes-operator:0.0.8
        imagePullPolicy: Always
        name: mongodb-kubernetes-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mongodb-kubernetes-operator
      serviceAccountName: mongodb-kubernetes-operator
      terminationGracePeriodSeconds: 30