apiVersion: operators.coreos.com/v1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: nvmesh-operator-go.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NVMesh is the Schema for the nvmeshes API
      displayName: NVMesh
      kind: NVMesh
      name: nvmeshes.nvmesh.excelero.com
      version: v1
  description: Excelero NVMesh Kubernetes Operator
  displayName: NVMesh Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nvmesh
  links:
  - name: Nvmesh Operator Go
    url: https://nvmesh-operator-go.domain
  maturity: alpha
  provider:
    name: Excelero
  version: 0.0.0
