apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nvmesh-operator
  name: nvmesh-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvmesh-operator
  template:
    metadata:
      labels:
        app: nvmesh-operator
    spec:
      serviceAccountName: nvmesh-operator
      containers:
      - name: controller
        image: excelero/nvmesh-operator:dev
        command:
        - /manager
        args:
        - --enable-leader-election
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
