apiVersion: nvmesh.excelero.com/v1alpha1
kind: NVMesh
metadata:
  name: cluster1
spec:
  core: {}
  management:
    version: "2.0.3-4"
    replicas: 3
  csi:
    version: "v1.1.0"
    controllerReplicas: 3