apiVersion: nvmesh.excelero.com/v1
kind: NVMesh
metadata:
  name: cluster1
spec:
  core:
    # The version for the Core components
    version: 2.2.1

    # Choose a specific version for the component images, please do not change this unless instructed by Excelero
    imageVersionTag: 0.8.0-17

    # Use TCP / IP - If false Infiniband is assumed
    tcpOnly: true

    # Define which network interfaces should be used for the storage data path
    configuredNICs: eth0

    # Define which NVMe drives should not be used by the NVMesh software
    excludeDrives:
      # A list of NVMe drive serial numbers that should not be used by the NVMesh software
      serialNumbers:
        - S3HCNX0K600408
        - S3HCNX0K600409

      # A list of device paths that should not be used by the NVMesh software
      devicePaths:
        - /dev/nvme1n1
        - /dev/nvme2n1

  csi:
    # The version of the NVMesh CSI driver
    version: v1.1.6-3
  management:
    mongoDB:
      replicas: 1
      # uncomment this to control parameters in the Mongo data volume PVC
      # dataVolumeClaim:
      #   storageClassName: some-storage-class
      #   selector:
      #     matchLabels:
      #       role: mongo-for-nvmesh

    # The number of Management servers in a High-Availability Management
    replicas: 1

    # The version of the NVMesh-Management server
    version: 2.2.0

    # uncomment this to control parameters of the management backups volume PVC
    # backupsVolumeClaim:
    #   # required storage-class for management backups volume
    #   storageClassName: sc-for-management
    #   # configure selectors to bound the PVC to a static-provisioned PV
    #   selector:
    #     matchLabels:
    #       role: nvmesh-backups
  actions:
    # Initiate logs collection on the NVMesh cluster
    # logs will be saved locally on each host at /opt/nvmesh-operator/logs
    - name: "collect-logs"

  # Internal debugging options
  debug:
    # This will try to pull all images even if they exist locally
    imagePullPolicyAlways: true

    # This will prevent containers from crashing causing the pod to be restarted
    containersKeepRunningAfterFailure: true

    # Adds additional debug prints to jobs for actions and uninstall
    debugJobs: false
  operator:
    # If IgnoreVolumeAttachmentOnDelete is true, The operator will allow deleting this cluster when there are active attachments of NVMesh volumes. This can lead to an unclean state left on the k8s cluster
    ignoreVolumeAttachmentOnDelete: false
    # If IgnorePersistentVolumesOnDelete is true, The operator will allow deleting this cluster when there are NVMesh PersistentVolumes on the cluster. This can lead to an unclean state left on the k8s cluster
    ignorePersistentVolumesOnDelete: false
    # If SkipUninstall is true, The operator will not clear the mongo db or remove files the NVMesh software has saved locally on the nodes. This can lead to an unclean state left on the k8s cluster
    SkipUninstall: false