apiVersion: nvmesh.excelero.com/v1
kind: NVMesh
metadata:
  name: cluster1
spec:
  core:
    azureOptimized: true
    configuredNICs: ib0
    version: 2.2.1
  csi:
    controllerReplicas: 1
    version: v1.1.4-7
  debug:
    containersKeepRunningAfterFailure: true
    imagePullPolicyAlways: true
  management:
    mongoDB:
      replicas: 1
    replicas: 1
    version: 2.2.0