apiVersion: nvmesh.excelero.com/v1
kind: NVMesh
metadata:
  name: cluster1
spec:
  core:
    configuredNICs: eth0
    version: 2.4.1-3
    tcpOnly: true
    imageVersionTag: 0.8.0-63-aks-2
    azureOptimized: true
    moduleParams: |
      options nvmeibs min_local_nvmeqs=32
      options nvmeibs max_local_nvmeqs=32
      options nvmeibs nr_max_channels_per_path_tcp=32
      options nvmeibc nr_max_channels_per_path_tcp=16
      options nvmeibc nr_max_channels_per_disk=32
      options nvmeibc nr_max_used_reqs_per_channel=8
      options siw notify_on_wq=N panic_on_rx_err=N debug_level=1 tx_flags_from_upstream=Y tx_flags_use_eor=Y comp_vector_cpu0=0
  csi:
    controllerReplicas: 1
    version: v1.1.7
  management:
    mongoDB:
      replicas: 1
      dataVolumeClaim:
        storageClassName: managed-premium
    replicas: 1
    version: 2.4.0-15
    backupsVolumeClaim:
      storageClassName: managed-premium
