---
# Source: nvmesh-csi-driver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nvmesh-csi-driver
spec:
  type: ClusterIP
  ports:
    - port: 12345
      name: dummy
  selector:
    app.kubernetes.io/name: nvmesh-csi-driver
    app.kubernetes.io/instance: nvmesh-csi-driver
