kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nvmesh-csi-controller
spec:
  serviceName: nvmesh-csi
  selector:
    matchLabels:
      nvmesh.excelero.com/component: csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        nvmesh.excelero.com/component: csi-controller
        app.kubernetes.io/name: nvmesh-csi-driver
        app.kubernetes.io/component: node-driver
      annotations:
        kubectl.kubernetes.io/default-container: nvmesh-csi-controller
    spec:
      serviceAccountName: nvmesh-csi
      containers:
        # NVMesh Driver
        - name: nvmesh-csi-controller
          image: "placeholder"
          imagePullPolicy: IfNotPresent
          env:
            - name: DRIVER_TYPE
              value: "Controller"
            - name: DRIVER_NAME
              value: "nvmesh-csi.excelero.com"
            - name: SOCKET_PATH
              value: unix:///csi/ctrl-csi.sock
            - name: MANAGEMENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nvmesh-csi-credentials
                  key: username
            - name: MANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nvmesh-csi-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: plugin-socket-dir
              mountPath: /csi
        # Provisioner
        - name: csi-provisioner
          image: "quay.io/k8scsi/csi-provisioner:v2.1.0"
          args:
            - "--feature-gates=Topology=true"
            - "--strict-topology"
            - "--immediate-topology"
            - "--extra-create-metadata"
            - "--csi-address=/csi/ctrl-csi.sock"
            - "--v=5"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi
        # Resizer
        - name: csi-resizer
          image: "quay.io/k8scsi/csi-resizer:v1.1.0"
          args:
            - "--v=5"
            - "--csi-address=/csi/ctrl-csi.sock"
            - "--leader-election"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: plugin-socket-dir
              mountPath: /csi
      volumes:
        - name: config-volume
          configMap:
            name: nvmesh-csi-config
        - name: plugin-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/nvmesh-csi.excelero.com/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory