apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-mongodb
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.1.57
    path: /mnt/pvForMongoDB