apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvmesh-client-driver-container
  labels:
    k8s-app: nvmesh-client-driver-container
spec:
  # TODO: This is not good enough - if a machine is both target and client we will have 2 mcs and agents
  # >> do we need another daemonset for 'converged'/ 'both' ?
  selector:
    matchLabels:
      name: nvmesh-driver-container
      nvmesh.driver-container-type: client
  template:
    metadata:
      labels:
        name: nvmesh-driver-container
        nvmesh.driver-container-type: client
    spec:
      nodeSelector:
        nvmesh.excelero.com/nvmesh-client: ""
      containers:
        - name: driver-container
          image: image-registry.openshift-image-registry.svc:5000/default/nvmesh-driver-container:b2
          command: ["/bin/bash", "-c", "/init.sh --type client --insert --remove-on-terminate --wait"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: lib-modules-dir
              mountPath: /host/lib/modules
            - name: var
              mountPath: /host/var/
          terminationGracePeriodSeconds: 60
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
        - name: lib-modules-dir
          hostPath:
            path: /lib/modules
        - name: var
          hostPath:
            path: /var
